### PR TITLE
Implement more anki-connect api calls

### PR DESCRIPTION
**Pull request by dlangevi**
I am hoping to use this package in my project (seen here https://github.com/dlangevi/read-chinese) it was previously all written in javascript but with the port over to go, I need to implement some additional anki-connect api calls.

I have tried to keep up the standard of testing you started with. 

The one decision I made which may be undesired is merging the anki-connect calls findNotes and notesInfo into a single function here (same with findCards and cardsInfo). I would prefer to keep it this way because I would assume normally this is what people would want, but would be happy to split it up if we are trying to mirror the anki-connect api as closely as possible

First time contributing to open source, so any feedback welcome

### CODE REVIEW

**Comment by atselvan** [comment]
> The one decision I made which may be undesired is merging the anki-connect calls findNotes and notesInfo into a single function here (same with findCards and cardsInfo). 

I do not mind your decision. One alternative implementation could be to add a method called Search which could do findNotes and return the cardIds, Search can then be consumed by Get combining findNotes and notesInfo just like you have implemented it currently. Something like this:


```
func (nm *notesManager) Search(query string) (*[]string, *errors.RestErr){
        noteIds, restErr := post[[]int64](nm.Client, ActionFindNotes, &findParams)
	        if restErr != nil {
		        return nil, restErr
	        }
        return noteIds, nil
}
```

```
func (nm *notesManager) Get(query string) (*[]ResultNotesInfo, *errors.RestErr) {
	findParams := ParamsFindNotes{
		Query: query,
	}
	noteIds, restErr := nm.Search(query)
	if restErr != nil {
		return nil, restErr
	}
...
```

This way Search could be used independently. I am not sure of a use case for this but it's always nice to make it a bit more modular.

**Comment by atselvan** [comment]
Please make sure all lines are covered by test cases. Also make sure to update the README file.

**Comment by dlangevi** [comment]
I like your suggestion, will change the api to be more like that

**Comment by dlangevi** [comment]
I was wondering if it is alright how I have directly returned restErr instead of checking it for nil first. Not sure if this goes agains a golang convention, but it seems more straightforward to directly return the error

**Comment by dlangevi** [comment]
Hey I see that you are not very active on Github lately. I would be happy to take more responsibility for this repo if you are not interested in being the lead maintainer going forwards. For now I will just continue make more changes on my fork and if you every log in again and want to figure something else out let me know.

**Comment by dlangevi** [comment]
I have now extensivly rewritten the testing framework to include verification of http requests being generated by the client. At this point it should be much faster for me to write new api methods and verify they conform to the expectations of anki-connect

**Comment by atselvan** [comment]
Sorry was on a long vacation :)

**Pull request merged**
